default_platform(:ios)

GIT_PATH = "https://github.com/gre4ixin/FlowDirection.git"

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    # git_pull
    jazzy
    # pod_repo_update(repo:GIT_PATH)
    # cocoapods
  end
end
